---
title: "Portfolio Loss Covid-19"
author: Raihan Ahmed
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    source_code: embed
---


```{r setup, message = FALSE}
library(tidyverse)
library(highcharter)
library(tidyquant)
library(timetk)
library(shinythemes)
```

Sidebar {.sidebar}
=====================================


```{r}

fluidRow(
  column(6,
  textInput("stock1", "iShares Russell", "IWM")),
  column(5,
  numericInput("w1", "Portf. %", 25, min = 1, max = 100))
)  

fluidRow(
  column(6,
  textInput("stock2", "SPDR Dow Jones Industrial Average", "DIA")),
  column(5,
  numericInput("w2", "Portf. %", 25, min = 1, max = 100))
)

fluidRow(
  column(6,
  textInput("stock3", "Crude oil", "USO")),
  column(5,
  numericInput("w3", "Portf. %", 20, min = 1, max = 100))
)

fluidRow(
  column(6,
  textInput("stock4", "Natural Gas", "UNG")),
  column(5,
  numericInput("w4", "Portf. %", 20, min = 1, max = 100))
)

fluidRow(
  column(6,
  textInput("stock5", "Biotech", "BBH")),
  column(5,
  numericInput("w5", "Portf. %", 10, min = 1, max = 100))
)


fluidRow(
  column(7,
  dateInput("date", "Starting Date", "2020-01-12", format = "yyyy-mm-dd"))
)

fluidRow(
  column(7,
  selectInput("rebalance", "rebalance freq",
              c("Monthly" = "months",
                "Weekly" = "weeks",
                "Daily" = "days",
                "Hourly" = "hours"))
  )
)


actionButton("go", "Calculate")


portfolio_decrease_xts <- eventReactive(input$go, {
  
  symbols <- c(input$stock1, input$stock2, input$stock3, input$stock4, input$stock5)
  
  prices <- getSymbols(symbols, src = 'yahoo', from = input$date, 
             auto.assign = TRUE, warnings = FALSE) %>% 
  map(~Ad(get(.))) %>% 
  reduce(merge) %>%
  `colnames<-`(symbols)

  w <- c(input$w1/100, input$w2/100, input$w3/100, input$w4/100, input$w5/100)

prices_monthly <- to.monthly(prices, indexAt = "last", OHLC = FALSE)
asset_returns_xts <- na.omit(Return.calculate(prices_monthly, method = "log"))

portfolio_decrease_xts <- 
  Return.portfolio(asset_returns_xts, 
                   wealth.index = 1, 
                   weights = w, 
                   rebalance_on = input$rebalance) %>% 
  `colnames<-`("decrease")

})


```

Portfolio Decrease
=====================================  

Row {data-height=500}
-----------------------------------------------------------------------

### Graph 1

```{r}
renderHighchart({
  highchart(type = "stock") %>%
  hc_title(text = "Decrease of a Dollar") %>%
  hc_add_series(portfolio_decrease_xts(), name = "Dollar Decrease", color = "cornflowerblue") %>%
  hc_navigator(enabled = FALSE) %>% 
  hc_scrollbar(enabled = FALSE) 
  
})
```


Row {data-height=500}
-------------------------------------

### Graph 2 

```{r}
renderPlot({
 
portfolio_decrease_xts() %>% 
    tk_tbl(preserve_index = TRUE, rename_index = "date") %>% 
    ggplot(aes(x = date)) +
    geom_line(aes(y = decrease), color = "cornflowerblue") +
    ylab("dollars") + 
    ggtitle("Decrease of Dollar over time")
})
```


Row {data-height=500}
-------------------------------------

```{r}
renderText({ 
    paste("A pneumonia of unknown cause was first reported on 31 December 2019. The outbreak was declared a Public Health Emergency of International Concern - on 30 January 2020.
          Economic turmoil associated with the COVID-19 pandemic has had wide-ranging and severe impacts upon financial markets, including stock, bond, and commodity (including crude oil and gold) markets. Major events included a described Russia–Saudi Arabia oil price war after failing to reach an OPEC+ agreement that resulted in a collapse of crude oil prices and a stock market crash in March 2020. ", input$var)
  })
  
```
